[theme]
base="dark"
primaryColor="#4d94ff"
secondaryBackgroundColor="#16161a"
font="monospace"




[server]
maxUploadSize = 10  # Максимальный размер загружаемых файлов в МБ
enableXsrfProtection = true  # Защита от CSRF-атак
enableCORS = false  # Отключаем CORS для безопасности

[browser]
gatherUsageStats = false  # Отключаем сбор статистики 