[theme]
primaryColor = "#4d94ff"  # Цвет неоновых рамок
backgroundColor = "#0e1117"  # Тёмный фон
secondaryBackgroundColor = "#1a1c24"  # Цвет для элементов интерфейса
textColor = "#fafafa"  # Цвет текста

[server]
maxUploadSize = 10  # Максимальный размер загружаемых файлов в МБ
enableXsrfProtection = true  # Защита от CSRF-атак
enableCORS = false  # Отключаем CORS для безопасности

[browser]
gatherUsageStats = false  # Отключаем сбор статистики 